### ISSUE TITLE
How to use it on fields?

### ISSUE THREAD

**Issue by micartey** [xxDark/Venuzdonoa#3]
Hello there,

In your README you wrote:
> Does it work with fields? Yes

However, there is no `makeFieldAccessor` or anything like that.
So… How do I use on fields?

**Comment by xxDark** [comment]
Get MHs to `objectFieldOffset`/`staticFieldOffset` in `jdk.internal.misc.Unsafe`. Use methods in `Unsafe` class to write/read values

**Comment by micartey** [comment]
That is a great idea — but just not what this project is about: Using the Unsafe class

But I will close this issue as this solves my problem.
